// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmNwLu80LXj0-qPHdObSksWP9dtQ9nk5E',
    appId: '1:6745281857:web:970ee55012291737773dc0',
    messagingSenderId: '6745281857',
    projectId: 'omeeo-web',
    authDomain: 'omeeo-web.firebaseapp.com',
    storageBucket: 'omeeo-web.firebasestorage.app',
    measurementId: 'G-V7WB228CYW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBgigsASVFH8nR0zhUnvGFjLUt-wjyyX8',
    appId: '1:6745281857:ios:12917f52eff2c955773dc0',
    messagingSenderId: '6745281857',
    projectId: 'omeeo-web',
    storageBucket: 'omeeo-web.firebasestorage.app',
    iosBundleId: 'com.example.omeeoweb',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN1EEf9RLl5xOCfJcTNiF1Wi-iOiNEnVE',
    appId: '1:6745281857:android:95ba8ead0a67a94c773dc0',
    messagingSenderId: '6745281857',
    projectId: 'omeeo-web',
    storageBucket: 'omeeo-web.firebasestorage.app',
  );

}